### ISSUE TITLE
[FEATURE REQUEST] IN operator support

### ISSUE THREAD

**Issue by ayZagen** [florajs/ql#6]
Hello, thanks for great library. Can you add support for `IN` operator?

Example usage:

`color IN [ "red", "blue"]`

**Comment by nicokaiser** [comment]
Depending on your implementation you can just use a list: 

```
colors="red","blue"
```

which generates an output like this:

```
[
  [
    { attribute: [ 'color' ], operator: '=', value: [ 'red', 'blue' ] }
  ]
]
```

**Comment by ayZagen** [comment]
I will use this library for generating sql and only missing functionality for my use cases is `IN` operator. With this library, thanks to you, querying database over rest will be such an easy task.

**Comment by not-implemented** [comment]
@ayZagen why don't you use our flora-sql-parser library for that?

https://github.com/godmodelabs/flora-sql-parser

It is especially for parsing and generating SQL.

**Comment by ayZagen** [comment]
@not-implemented IMHO It is unpleasant to pass over SQL statements in REST API. `flora-sql-parser` won't be fitting in my needs. I was looking something like lucene query syntax and I am glad to find flora-ql.

**Comment by not-implemented** [comment]
@ayZagen ah, I understand ... that is exactly what our lightweight "flora" API framework does:

https://github.com/godmodelabs/flora

Maybe it is interesting for you (flora-ql and flora-sql-parser are components of it)

**Comment by ayZagen** [comment]
yep, I have seen that and will definitely try it out on new projects, seems really promising. Right now I would implement this to an existing project.
